[program:websockify]
command=websockify --web /usr/share/novnc 6080 localhost:5900
autorestart=true
priority=450
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/websockify.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true
